Repository InnoQueue/Backend, pull requests merged in 2022-09, with the labels that each got.

#19 Add .idea folder in gitignore
  .gitignore
Labels: routine

#27 Update README #26
  README.md
Labels: routine

#30 Add github action to build project after PR #24
  .github/workflows/build.yml
  src/test/kotlin/com/innopolis/innoqueue/InnoQueueApplicationTests.kt
Labels: routine

#31 Add detekt check style #23
  build.gradle.kts
  config/detekt.yml
  src/main/kotlin/com/innopolis/innoqueue/InnoQueueApplication.kt
  src/main/kotlin/com/innopolis/innoqueue/controller/DatabaseController.kt
  src/main/kotlin/com/innopolis/innoqueue/controller/QueueController.kt
  src/main/kotlin/com/innopolis/innoqueue/dto/NewQueueDTO.kt
  src/main/kotlin/com/innopolis/innoqueue/dto/UserExpensesDTO.kt
  src/main/kotlin/com/innopolis/innoqueue/model/UserQueue.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/DatabaseRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/NotificationRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/QueuePinCodeRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/QueueQrCodeRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/QueueRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/UserQueueRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/UserRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/repository/UserSettingsRepository.kt
  src/main/kotlin/com/innopolis/innoqueue/service/DatabaseService.kt
  src/main/kotlin/com/innopolis/innoqueue/service/NotificationsService.kt
  src/main/kotlin/com/innopolis/innoqueue/service/QueueService.kt
  src/main/kotlin/com/innopolis/innoqueue/service/ToDoTaskService.kt
  src/main/kotlin/com/innopolis/innoqueue/service/UserService.kt
  src/main/kotlin/com/innopolis/innoqueue/utils/MessagePushNotificationCreator.kt
  src/test/kotlin/com/innopolis/innoqueue/InnoQueueApplicationTests.kt
Labels: routine

#35 Update dependencies #34
  build.gradle.kts
  gradle.properties
Labels: routine

#38 Prepare project for heroku deployment closes #37
  .gitignore
  Procfile
  restore.sql
  src/main/resources/innoqueue-firebase.json.origin
  system.properties
Labels: routine

#40 Flyway migrations for heroku
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: routine

#41 Update .gitignore
  .gitignore
Labels: routine

#48 Fix admin authorisation availability closes #36
  src/main/kotlin/com/innopolis/innoqueue/service/UserService.kt
Labels: feature

#49 Minor fix pre-push
  .githooks/pre-push
Labels: bug

#50 Minor fix app and flyway startup
  src/main/kotlin/com/innopolis/innoqueue/InnoQueueApplication.kt
  src/main/resources/db/migration/V3__INSERT_DATA.sql
Labels: feature

#51 Minor add application test profile
  src/main/resources/application-test.yml
Labels: feature

#52 Update firebase credentials config closes #42
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/innopolis/innoqueue/configs/FirebaseConfiguration.kt
  src/main/kotlin/com/innopolis/innoqueue/service/FirebaseMessagingNotificationsService.kt
  src/main/resources/innoqueue-firebase.json.origin
Labels: feature

#53 Minor firebase credentials
  src/main/kotlin/com/innopolis/innoqueue/configs/FirebaseConfiguration.kt
  src/main/resources/application.yml
Labels: feature
